<?php
// $Id$

/*
 * Modify the '--- change this ---' part below to (part of) the dev address you
 * always use when building sites. This way the e-mail check will function
 * properly for your environment.
 * This was not put in a settings form to allow for easy deployment on many
 * without having to adjust settings all the time. Strongarm seemed overkill.
 * Maybe I'll rethink this, not sure about it.
 */
define('PRODCHECK_EMAIL', '--- change this ---');

/**
 * This one is for use with the XMLRPC API, so that you have proper links when
 * using the prod_monitor module.
 */
$protocol = 'http://';
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
  $protocol = 'https://';
}
define('PRODCHECK_BASEURL', $protocol.$_SERVER['SERVER_NAME'].'/');

/**
 * Our own definition of the core requirements states. These can be found in
 * includes/install.inc and are only available in hook_install(). That's why
 * we redefine them here (yes, it's double!). It's nicer than including the
 * install.inc file...
 * Let's see if this will pose problems...
 */
define('REQUIREMENT_INFO', -1);
define('REQUIREMENT_OK', 0);
define('REQUIREMENT_WARNING', 1);
define('REQUIREMENT_ERROR', 2);

/**
 * Our own definition of the Nagios module's states. Don't see any other way to
 * do this. If you do, drop me a line in the issue queue.
 */
define('NAGIOS_STATUS_OK', 0);
define('NAGIOS_STATUS_UNKNOWN', 1);
define('NAGIOS_STATUS_WARNING', 2);
define('NAGIOS_STATUS_CRITICAL', 3);

/**
 * Implementation of hook_help().
 */
function prod_check_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#prod_check':
      $output .= '<p>'.t('Production check is a module that will add a report detailing the status of several settings and modules. The report is tailored for a <strong>production environment</strong>. It will tell you which modules should (not) be running, what settings are OK or not and much more. It is an easy way to have an overview of the status of your site when bringing it live, so that you can quickly put all the configuration details in order to be ready for production use.').'</p>';
      $output .= '<p>'.t('Using the settings page, you can enable <strong>XMLRPC support</strong> so that it can report back to the <strong>Production monitor</strong> module, available as an extra module in this package. If you install the <em>Production monitor</em> module on a central site, you can monitor several sites in a glance, ensuring that no one changes settings without you knowing about it. See the <em>Production monitor</em> built in help for more information.').'</p>';
      $output .= '<p>'.t('If you prefer using <strong>!link</strong> for monitoring, you can simply enable support for that on the settings page by ticking the appropriate checkmark. An extra set of checkboxes will appear, allowing you to configure in detail what exactly you wish !link to monitor.', prod_check_link_array('Nagios', 'http://drupal.org/project/nagios')).'</p>';
      break;
    case 'admin/reports/prod-check':
      $output .= '<p>'.t('This is an overview of all checks performed by the <em>Production check</em> module and their status. You can click the links inside the report to jump to the module\'s settings page, or to go to the project page of a module, in case you need to download it for installation.').'</p>';
      break;
    case 'admin/settings/prod-check':
      $output .= '<p><strong>'.t('Enable XMLRPC API').'</strong><br />';
      $output .= t('By ticking this box, you open up the module\'s XMLRPC functions so they can be called by the <strong>Production monitor</strong> module for remote monitoring of your site. When enabling XMLRPC, you <strong>must</strong> enter an <strong>API key</strong> to secure the transfer of data. It\'s limited to 128 characters. A mixture of alphanumeric and special characters will increase security.').'</p>';
      $output .= '<p><strong>'.t('Enable Nagios integration').'</strong><br />';
      $output .= t('By ticking this box, you open up the module\'s Nagios hooks, so that it can interface with the !link module. You will obviously need to install this module next to <em>Production check</em> to enable this functionality.', prod_check_link_array('Nagios', 'http://drupal.org/project/nagios')).'<br />';
      $output .= t('When the checkbox is enabled, a new array of checkboxes will appear, allowing you to specify in detail what will be reported to !link.', prod_check_link_array('Nagios', 'http://drupal.org/project/nagios')).'</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_perm()
 */
function prod_check_perm() {
  return array('access production check');
}

/**
 * Implementation of hook_menu()
 */
function prod_check_menu() {
  $items = array();

  $items['admin/reports/prod-check'] = array(
    'title' => t('Production check'),
    'description' => t('View the Production check report page.'),
    'page callback' => 'prod_check_status',
    'access callback' => 'user_access',
    'access arguments' => array('access production check'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/prod_check.admin.inc',
  );

  $items['admin/settings/prod-check'] = array(
    'title' => t('Production check'),
    'description' => t('Setup the Production check module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prod_check_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('access production check'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/prod_check.admin.inc',
  );
  $items['admin/settings/prod-check/nagios'] = array(
    'title' => t('Production check Nagios settings'),
    'page callback' => 'prod_check_enable_nagios',
    'access callback' => 'user_access',
    'access arguments' => array('access production check'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/prod_check.admin.inc',
  );


  $items['admin/reports/status/apc'] = array(
    'title' => t('APC'),
    'page callback' => 'prod_check_apc',
    'access callback' => 'user_access',
    'access arguments' => array('access production check'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/prod_check.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_xmlrpc
 * http://api.drupal.org/api/drupal/developer--hooks--core.php/function/hook_xmlrpc/6
 */
function prod_check_xmlrpc() {
  if (variable_get('prod_check_enable_xmlrpc', 0) == 1) {
    return array(
      array(
        'prod_check.get_settings',
        'prod_check_get_settings',
        array('struct', 'string'),
        t('Returns a struct containing a form to be displayed on the prod_monitor module\'s settings page for site specific configuration.')
      ),
      array(
        'prod_check.get_data',
        'prod_check_get_data',
        array('struct', 'string', 'struct'),
        t('Returns a struct containing the result of all requested checks.')
      ),
    );
  }
}


/**
 * Helper function to check for correct API key.
 */
function _prod_check_valid_key($ping_key) {
  $connect_key = variable_get('prod_check_xmlrpc_key', '');

  $result = FALSE;
  if ($connect_key && $ping_key == $connect_key) {
    $result = TRUE;
  }

  return $result;
}

/**
 * XMLRPC version of _prod_check_functions()
 * Returnes a keyed array of functions that can be parsed by the reciever into
 * a form or status page.
 */
function prod_check_get_settings($ping_key) {
  $data = FALSE;

  if (_prod_check_valid_key($ping_key)) {
    $data = _prod_check_functions();
  }

  return $data;
}
/**
 * XMLRPC callback function that returns all data of requested checks.
 *
 * @param ping_key Api key for this site
 * @param checks   Array of all checks to perform
 *
 * @return Array of all data to be displayed by the requesting site in a
 * 'status_form' theme.
 */
function prod_check_get_data($ping_key, $checks) {
  $data = FALSE;

  if (_prod_check_valid_key($ping_key)) {
    $data = array();
    foreach ($checks as $set => $calls) {
      $data[$set] = array();
      foreach ($calls as $key => $function) {
        $func = '_prod_check_' . $function;
        // $func() will execute the function with the name we composed above.
        $data[$set] = array_merge($data[$set], $func('xmlrpc'));
      }
    }
  }

  return $data;
}

/**
 * Nagios support, see http://drupal.org/project/nagios
 */

/**
 * Implementation of hook_nagios_info()
 */
function prod_check_nagios_info() {
  if (variable_get('prod_check_enable_nagios', 0)) {
    return array(
      'name'   => 'Production check',
      'id'     => 'PRDCHK',
    );
  }
}

/**
 * Implementation of hook_nagios_settings()
 */
/*function prod_check_nagios_settings() {
  if (variable_get('prod_check_enable_nagios', 0)) {
    foreach(prod_check_functions() as $function => $description) {
      $var = 'prod_check_' . $function;
      $form[$var] = array(
        '#type'          => 'checkboxes',
        '#title'         => $function,
        '#default_value' => variable_get($var, TRUE),
        '#description' => $description,
      );
    }
  }
}*/

/**
 * Implementation of hook_nagios()
 */
function prod_check_nagios() {
  if (variable_get('prod_check_enable_nagios', 0)) {
    $status = array();
    $checks = variable_get('prod_check_nagios_checks', array());
    foreach ($checks as $set => $calls) {
      foreach ($calls as $key => $function) {
        $func = '_prod_check_' . $function;
        // $func() will execute the function with the name we composed above.
        $status = array_merge($status, $func('nagios'));
      }
    }
    return $status;
  }
}

/**
 * Function that gives status feedback on requirements.
 *
 * @param checks an associative array of associative arrays consisting of the
 *              following keys:
 *                #title: the title to be displayed in the status table
 *                #state: true or false, see examples on how to use this
 *                #severity: the severity when the check fails
 *                #value_ok: value to show when check will pass
 *                #value_nok: to show when check will fail
 *                #description_ok: description to show when check will pass
 *                #description_nok: description to show when check will fail
 *
 * @return array result erray that can be themed with the 'status_report' theme.
 */
function prod_check_execute_check($checks, $caller) {
  $result = array();

  if (is_array($checks)) {
    foreach (element_children($checks) as $key) {
      if (!$checks[$key]['#state']) {
        // Check failed
        switch ($caller) {
          case 'internal':
          case 'xmlrpc':
            $result[$key] = array(
              'title' => $checks[$key]['#title'],
              'value' => $checks[$key]['#value_nok'],
              'severity' => $checks[$key]['#severity'],
              'description' => $checks[$key]['#description_nok'],
            );
            break;
          case 'nagios':
            $result[$checks[$key]['#nagios_key']] = array(
              'status' => $checks[$key]['#severity'], 
              'type'   => $checks[$key]['#nagios_type'],
              'text'   => $checks[$key]['#description_nok'],
            );
            break;
        }
      }
      else {
        // Check passed
        switch ($caller) {
          case 'internal':
          case 'xmlrpc':
            $result[$key] = array(
              'title' => $checks[$key]['#title'],
              'value' => $checks[$key]['#value_ok'],
              'severity' => REQUIREMENT_OK,
              'description' => $checks[$key]['#description_ok'],
            );
            break;
          case 'nagios':
            $result[$checks[$key]['#nagios_key']]  = array(
              'status' => NAGIOS_STATUS_OK, 
              'type'   => $checks[$key]['#nagios_type'],
              'text'   => $checks[$key]['#description_ok'],
            );
            break;
        }
      }
    }
  }

  return $result;
}

/**
 * Helper function to generate generic 'settings OK' description.
 */
function prod_check_ok_title($title, $path, $text = 'Your !link settings are OK for production use.') {
  return t($text, array('!link' => '<em>'.l(t($title), $path, array('attributes' => array('title' => t($title)))).'</em>'));
}

/**
 * Helper function to generate link array to pass to the t() function
 */
function prod_check_link_array($title, $path) {
  return array('!link' => '<em>'.l(t($title), $path, array('attributes' => array('title' => t($title)))).'</em>');
}

// --- All check functions follow here ---

/**
 * Keyed array containing all check functions and their description so they can
 * be easily executed from a simple loop.
 * If you add a new function, add it here as well, or it will never be executed.
 * NOTE: NO use of t() here since we'll be doing that later! This content has to
 *       be translated by the site displaying it: Prod check or Prod monitor!
 */
function _prod_check_functions() {
  $functions = array();

  // Settings
  $functions['settings'] = array(
    'title' => 'Settings',
    'description' => 'Checks wether various settings are fit for a production environment.',
    'functions' => array(
      'error_reporting' =>  'Error reporting',
      'user_register' => 'User registration',
      'site_mail' => 'Site e-mail',
    ),
  );

  // Server
  $functions['server'] = array(
    'title' => 'Server',
    'description' => 'Checks certain server side parameters such as APC.',
    'functions' => array(
      'apc' => 'APC',
      'release_notes' => 'Release notes',
    ),
  );

  // Performance settings
  $functions['performance'] = array(
    'title' => 'Performance',
    'description' => 'Checks if performance settings are OK for production use.',
    'functions' => array(
      'page_cache' => 'Page caching',
      'page_compression' => 'Page compression',
      'block_cache' => 'Block cache',
      'preprocess_css' => 'Optimize CSS files',
      'preprocess_js' => 'Optimize JavaScript files',
    ),
  );

  // Modules
  $functions['modules'] = array(
    'title' => 'Modules',
    'description' => 'Checks if certain modules are on or off and if they\'re properly configured.',
    'functions' => array(
      'update_status' => 'Update status',
      'devel' => 'Devel',
      'search_config' => 'Search config',
    ),
  );

  // SEO
  $functions['seo'] = array(
    'title' => 'SEO',
    'description' => 'Checks if basic SEO modules are enabled.',
    'functions' => array(
      'googleanalytics' => 'Google Analytics',
      'nodewords' => 'Meta tags',
      'page_title' => 'Page titles',
      'pathauto' => 'Path auto',
      'path_redirect' => 'Path redirect',
      'xmlsitemap' => 'XML sitemap',
    ),
  );

  return $functions;
}

/**
 * Parse the functions array and return a form fieldset with different sets of
 * checkboxes so it can be inserted 'as is' in another form array for rendering.
 * This is primlarily still here for integration with Nagios. Though not in use
 * now since Nagios would create far too much needless variables in my personal
 * opinion. It's left in for easy future integration with the
 * hook_nagios_settings().
 */
function _prod_check_functions_as_form() {
  $form = array();

  $form['prod_check_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Configure what data you wish to monitor with <strong>Nagios</strong> for this site.'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['prod_check_settings']['monitor_settings'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id="prod-check-settings">',
    '#suffix' => '</div>',
    '#tree' => TRUE,
  );

  $i = 1;
  foreach (_prod_check_functions() as $set => $data) {
    $rest = $i%2;
    $form['prod_check_settings']['monitor_settings'][$set] = array(
      '#type' => 'checkboxes',
      '#title' => t($data['title']),
      '#description' => t($data['description']),
      '#options' => $data['functions'],
      '#default_value' => array_keys($data['functions']),
      '#prefix' => '<div class="prod-check-settings '.(($rest) ? 'odd' : 'even').'">',
      '#suffix' => '</div>',
    );
    $i++;
  }

  return $form;
}

// --- SETTINGS ---
// TODO: find a solution of the use of t() here. Should be used on the site
// displaying the content! Maybe use a custom theme instead of
// theme_status_report()...? Any ideas?

// Error reporting check
function _prod_check_error_reporting($caller = 'internal') {
  $check = array();

  $title = 'Error reporting';
  $setting1 = t('Write errors to the log and to the screen');
  $setting2 = t('Write errors to the log');
  $path = 'admin/settings/error-reporting';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_error_reporting'] = array(
    '#title' => t($title),
    '#state' => variable_get('error_level', 1) != 1,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR,
    '#value_ok'  => $setting2,
    '#value_nok'  => $setting1,
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => t('Your !link settings are set to %setting1, they should be set to %setting2 on a producion environment!',
      array(
        '!link' => '<em>'.l(t($title), $path, array('attributes' => array('title' => t($title)))).'</em>',
        '%setting1' => $setting1,
        '%setting2' => $setting2,
      )
    ),
    '#nagios_key' => 'ERR',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// User register settings check
function _prod_check_user_register($caller = 'internal') {
  $check = array();

  $title = 'User registration';
  $setting1 = t('Visitors can create accounts and no administrator approval is required');
  $setting2 = t('Visitors can create accounts but administrator approval is required');
  $path = 'admin/user/settings';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_user_register'] = array(
    '#title' => t($title),
    '#state' => variable_get('user_register', 1) != 1,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => $setting2,
    '#value_nok'  => $setting1,
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => t('Your !link settings are set to %setting1. Are you sure this is what you want and did not mean to use %setting2? With improperly setup access rights, this can be dangerous...',
      array(
        '!link' => '<em>'.l(t($title), $path, array('attributes' => array('title' => t($title)))).'</em>',
        '%setting1' => $setting1,
        '%setting2' => $setting2,
      )
    ),
    '#nagios_key' => 'USR',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// Site e-mail address check
function _prod_check_site_mail($caller = 'internal') {
  $check = array();

  $title = 'Site e-mail';
  $path = 'admin/settings/site-information';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $site_mail = variable_get('site_mail', '');

  $check['prod_check_site_mail'] = array(
    '#title' => t($title),
    '#state' => $site_mail != '' && !preg_match('/'.PRODCHECK_EMAIL.'/i', $site_mail),
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR,
    '#value_ok'  => t('Global site e-mail address OK: %mail', array('%mail' => $site_mail)),
    '#value_nok'  => t('Global site e-mail address set to %mail', array('%mail' => $site_mail)),
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => t('The global e-mail address of the website should not be a Nascom address on production sites!'),
    '#nagios_key' => 'MAIL',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// --- SERVER ---

// APC check
function _prod_check_apc($caller = 'internal') {
  $check = array();

  $title = 'APC';
  $path = 'admin/reports/status/apc';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  if (!function_exists('apc_cache_info')) {
	  $desc_nok = t('!link does not appear to be running.', prod_check_link_array($title, $path));
    $val_nok = t('Disabled');
    $error = TRUE;
  }
  else if ($cache = @apc_cache_info('opcode')) {
    if ($cache['num_misses'] >= $cache['num_hits']) {
  	  $desc_nok = t('!link not properly configured, too many misses', prod_check_link_array($title, $path)) .': '.t('hits').': '.$cache['num_hits'].', '.t('misses').': '.$cache['num_misses'].'.';
      $val_nok = t('Not functioning properly.');
      $error = TRUE;
    }
    else if ($cache['num_misses'] < $cache['num_hits']) {
  	  $desc_ok = t('!link running fine', prod_check_link_array($title, $path)) .': '.t('hits').': '.$cache['num_hits'].', '.t('misses').': '.$cache['num_misses'].'.';
      $val_ok = t('Enabled');
      $error = FALSE;
    }
  }
  else {
    $desc_nok = t('Could not retrieve !link cache data.', prod_check_link_array($title, $path));
    $val_nok = t('Not functioning properly.');
    $error = TRUE;
  }

  $check['prod_check_apc'] = array(
    '#title' => t($title),
    '#state' => !$error,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => $desc_ok,
    '#description_nok' => $desc_nok,
    '#nagios_key' => 'APC',
    '#nagios_type' => 'perf',
  );

  return prod_check_execute_check($check, $caller);
}

// .txt files present in root check
function _prod_check_release_notes($caller = 'internal') {
  $check = array();
  $title = 'Release notes';

  $files = array(
    'CHANGELOG.txt',
    'COPYRIGHT.txt',
    'INSTALL.mysql.txt',
    'INSTALL.pgsql.txt',
    'INSTALL.txt',
    'LICENSE.txt',
    'MAINTAINERS.txt',
    'UPGRADE.txt',
  );

  $error = FALSE;
  for ($i = 0; $i < count($files); $i++) {
    // It would seem that $_SERVER['DOCUMENT_ROOT'] is not always set, hence the
    // use of realpath() in combination with base path to determine the full
    // path to the Drupal installation.
    if (file_exists(realpath('.'.base_path()).'/'.$files[$i])) {
      $error = TRUE;
      break;
    }
  }

  $check['prod_check_release_notes'] = array(
    '#title' => t($title),
    '#state' => !$error,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => t('Release note .txt files have been removed.'),
    '#value_nok'  => t('Release note .txt files still present on your server!'),
    '#description_ok'  => t('Status is OK for production use.'),
    '#description_nok' => t('Leaving the release note .txt files present on the webserver is a minor security risk. These files are useless on production anyway and simply should not be there!'),
    '#nagios_key' => 'REL',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// --- PERFORMANCE ---
//TODO: add/integrate boost checks!

// Page cache
function _prod_check_page_cache($caller = 'internal') {
  $check = array();

  $title = 'Page caching';
  $path = 'admin/settings/performance';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_page_cache'] = array(
    '#title' => t($title),
    '#state' => variable_get('cache', 0) != 0,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => t('Your !link settings are disabled. You should at least set page caching to Normal on production sites!', prod_check_link_array($title, $path)),
    '#nagios_key' => 'PCACHE',
    '#nagios_type' => 'perf',
  );

  return prod_check_execute_check($check, $caller);
}

// Page compression
function _prod_check_page_compression($caller = 'internal') {
  $check = array();

  $title = 'Page compression';
  $path = 'admin/settings/performance';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_page_compression'] = array(
    '#title' => t($title),
    '#state' => variable_get('page_compression', 0) != 0,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => t('Your !link settings are disabled. You should enable page compression on production sites!', prod_check_link_array($title, $path)),
    '#nagios_key' => 'PCOMP',
    '#nagios_type' => 'perf',
  );

  return prod_check_execute_check($check, $caller);
}

// Block cache
function _prod_check_block_cache($caller = 'internal') {
  $check = array();

  $title = 'Block cache';
  $path = 'admin/settings/performance';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_block_cache'] = array(
    '#title' => t($title),
    '#state' => variable_get('block_cache', 0) != 0,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => t('Your !link settings are disabled. You should really enable this for production as it can cause huge performance increases, especially on high load websites!', prod_check_link_array($title, $path)),
    '#nagios_key' => 'BCACHE',
    '#nagios_type' => 'perf',
  );

  return prod_check_execute_check($check, $caller);
}

// Optimize CSS files
function _prod_check_preprocess_css($caller = 'internal') {
  $check = array();

  $title = 'Optimize CSS files';
  $path = 'admin/settings/performance';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_preprocess_css'] = array(
    '#title' => t($title),
    '#state' => variable_get('preprocess_css', 0) != 0,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => t('Your !link settings are disabled, they should be enabled on a producion environment! This should not cause trouble if you steer clear of @import statements.', prod_check_link_array($title, $path)),
    '#nagios_key' => 'CCOMP',
    '#nagios_type' => 'perf',
  );

  return prod_check_execute_check($check, $caller);
}

// Optimize JavaScript files
function _prod_check_preprocess_js($caller = 'internal') {
  $check = array();

  $title = 'Optimize JavaScript files';
  $path = 'admin/settings/performance';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_preprocess_js'] = array(
    '#title' => t($title),
    '#state' => variable_get('preprocess_js', 0) != 0,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => t('Your !link settings are disabled, ideally they should be enabled on a producion environment but this requires testing first, since it can cause JavaScript errors in certain cases.', prod_check_link_array($title, $path)),
    '#nagios_key' => 'JCOMP',
    '#nagios_type' => 'perf',
  );

  return prod_check_execute_check($check, $caller);
}

// --- MODULES ---

// Update status
function _prod_check_update_status($caller = 'internal') {
  $check = array();

  $title = 'Update status';
  $path = 'admin/reports/updates';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_update_status'] = array(
    '#title' => t($title),
    '#state' => !module_exists('update'),
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => t('Your settings are OK for production use.'),
    '#description_nok' => t('You have enabled the !link module. It would be better to turn this off on production, contrary to what Drupal core claims, and keep it running on development. Updating and testing should happen on development before deploying to production anyway.', prod_check_link_array($title, $path)),
    '#nagios_key' => 'UPD',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// Devel
function _prod_check_devel($caller = 'internal') {
  $checks = array();

  $modules = array(
    'DVL' => array(
      'name' => 'devel',
      'title' => 'Devel',
      'path' => 'admin/settings/devel',
    ),
    'DVG' => array(
      'name' => 'devel_generate',
      'title' => 'Devel generate',
      'path' => 'admin/generate',
    ),
    'DVN' => array(
      'name' => 'devel_node_access',
      'title' => 'Devel node access',
      'path' => 'admin/settings/devel',
    ),
    'DVT' => array(
      'name' => 'devel_themer',
      'title' => 'Theme developer',
      'path' => 'admin/settings/devel_themer',
    ),
  );

  foreach ($modules as $key => &$data) {
    $data['error'] = (module_exists($data['name'])) ? TRUE : FALSE;
    $title = $data['title'];
    $path = $data['path'];
    if ($caller != 'internal') {
      $path = PRODCHECK_BASEURL . $path;
    }

    $checks['prod_check_'.$data['name']] = array(
      '#title' => t($title),
      '#state' => !$data['error'],
      '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR,
      '#value_ok'  => t('Disbled'),
      '#value_nok'  => t('Enabled'),
      '#description_ok'  => t('Your settings are OK for production use.'),
      '#description_nok' => t('You have enabled the !link module. This should not be running on a production environment!', prod_check_link_array($title, $path)),
      '#nagios_key' => $key,
      '#nagios_type' => 'state',
    );
  }

  return prod_check_execute_check($checks, $caller);
}

// Search config
function _prod_check_search_config($caller = 'internal') {
  $check = array();
  $error = FALSE;

  $title = 'Search config';
  $path = 'admin/settings/search';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  if (!module_exists('search_config')) {
    $error = TRUE;
    $severity = ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING;
    $value_nok = t('Disabled');
    $msg_nok = t('You have not enabled the !link module. Please double check if you need this module or not, to be able to hide certain content types from being searched by users.', prod_check_link_array($title, 'http://drupal.org/project/search_config'));
  }
  else {
    $search_config = variable_get('search_config_disable_type', array());
    $error = TRUE;
    foreach ($search_config as $key => $value) {
      if (is_string($value)) {
        $error = FALSE;
        break;
      }
    }
    if ($error) {
      $severity = ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR;
      $value_nok = t('Not properly configured.');
      $msg_nok = t('You have enabled the !link module, but no content types are excluded from being searched!', prod_check_link_array($title, $path));
    }
  }

  $check['prod_check_search_config'] = array(
    '#title' => t($title),
    '#state' => !$error,
    '#severity' => $severity,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => $value_nok,
    '#description_ok'  => prod_check_ok_title($title, $path),
    '#description_nok' => $msg_nok,
    '#nagios_key' => 'SRCH',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// --- SEO ---

// TODO: mage generic function for all of these, only $title, $path & $key change!

// Google Analytics
function _prod_check_googleanalytics($caller = 'internal') {
  $check = array();
  $error = FALSE;
  $ga_account = variable_get('googleanalytics_account', 'UA-');

  $title_ok = 'settings';
  $text_ok = 'Check the !link to verify if they are as you expect.';

  $title = 'Google Analytics';
  $path = 'admin/settings/googleanalytics';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  if (!module_exists('googleanalytics')) {
    $error = TRUE;
    $severity = ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING;
    $value_nok = t('Disabled');
    $msg_nok = t('You have not enabled the !link module. If you wish to track and optimise your site !link is absolutely necessary.', prod_check_link_array($title, 'http://drupal.org/project/google_analytics'));
  }
  else if (empty($ga_account) || $ga_account == 'UA-') {
    $error = TRUE;
    $severity = ($caller == 'nagios') ? NAGIOS_STATUS_CRITICAL : REQUIREMENT_ERROR;
    $value_nok = t('Not properly configured.');
    $msg_nok = t('You did not !link! Tracking will not be functional!', prod_check_link_array('enter a Google Analytics account', $path));
  }

  $check['prod_check_googleanalytics'] = array(
    '#title' => t($title),
    '#state' => !$error,
    '#severity' => $severity,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => $value_nok,
    '#description_ok'  => prod_check_ok_title($title_ok, $path, $text_ok),
    '#description_nok' => $msg_nok,
    '#nagios_key' => 'GA',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// Meta tags (nodewords)
function _prod_check_nodewords($caller = 'internal') {
  $check = array();
  $title_ok = 'settings';
  $text_ok = 'Check the !link to verify if they are as you expect.';

  $title = 'Meta tags';
  $path = 'admin/content/nodewords';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_nodewords'] = array(
    '#title' => t($title),
    '#state' => module_exists('nodewords'),
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title_ok, $path, $text_ok),
    '#description_nok' => t('You have not enabled the !link module. If you care about ranking your site in search engines, this module is an absolute must.', prod_check_link_array($title, 'http://drupal.org/project/nodewords')),
    '#nagios_key' => 'META',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

function _prod_check_page_title($caller = 'internal') {
  $check = array();
  $error = FALSE;
  $pager = variable_get('page_title_pager_pattern', '');

  $title_ok = 'settings';
  $text_ok = 'Check the !link to verify if they are as you expect.';

  $title = 'Page titles';
  $path = 'admin/content/page_title';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }
  if (!module_exists('page_title')) {
    $error = TRUE;
    $value_nok = t('Disabled');
    $msg_nok = t('You have not enabled the !link module. This module can help out with problems such as pages with paging being marked as duplicate content by search engines.', prod_check_link_array($title, 'http://drupal.org/project/page_title'));
  }
  else if (empty($pager)) {
    $error = TRUE;
    $value_nok = t('Not properly configured.');
    $msg_nok = t('You have not !link You shoul dreally do this if you want proper Google Indexing.', prod_check_link_array('set a pager pattern', $path));
  }

  $check['prod_check_page_title'] = array(
    '#title' => t($title),
    '#state' => !$error,
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => $value_nok,
    '#description_ok'  => prod_check_ok_title($title_ok, $path, $text_ok),
    '#description_nok' => $msg_nok,
    '#nagios_key' => 'PTIT',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// Pathauto
function _prod_check_pathauto($caller = 'internal') {
  $check = array();
  $title_ok = 'settings';
  $text_ok = 'Check the !link to verify if they are as you expect.';

  $title = 'Path auto';
  $path = 'admin/build/path/pathauto';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_pathauto'] = array(
    '#title' => t($title),
    '#state' => module_exists('pathauto'),
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title_ok, $path, $text_ok),
    '#description_nok' => t('You have not enabled the !link module. This module is a must for search engines. Pathauto will automatically generate human readable URLs for every piece of content in the site.', prod_check_link_array($title, 'http://drupal.org/project/pathauto')),
    '#nagios_key' => 'PATH',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// Path redirect
function _prod_check_path_redirect($caller = 'internal') {
  $check = array();
  $title_ok = 'settings';
  $text_ok = 'Check the !link to verify if they are as you expect.';

  $title = 'Path redirect';
  $path = 'admin/build/path-redirect';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_path_redirect'] = array(
    '#title' => t($title),
    '#state' => module_exists('path_redirect'),
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title_ok, $path, $text_ok),
    '#description_nok' => t('You have not enabled the !link module. This module ensures, when properly configured, that when paths for content are changhed, the old paths are given a 301 redirect to the new paths.', prod_check_link_array($title, 'http://drupal.org/project/path_redirect')),
    '#nagios_key' => 'REDIR',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}

// XML sitemap
function _prod_check_xmlsitemap($caller = 'internal') {
  $check = array();
  $title_ok = 'settings';
  $text_ok = 'Check the !link to verify if they are as you expect.';

  $title = 'XML sitemap';
  $path = 'admin/settings/xmlsitemap';
  if ($caller != 'internal') {
    $path = PRODCHECK_BASEURL . $path;
  }

  $check['prod_check_xmlsitemap'] = array(
    '#title' => t($title),
    '#state' => module_exists('xmlsitemap'),
    '#severity' => ($caller == 'nagios') ? NAGIOS_STATUS_WARNING : REQUIREMENT_WARNING,
    '#value_ok'  => t('Enabled'),
    '#value_nok'  => t('Disabled'),
    '#description_ok'  => prod_check_ok_title($title_ok, $path, $text_ok),
    '#description_nok' => t('You have not enabled the !link module. This module generates an XML sitemap which can be submitted to search engines, guaranteeing optimal indexation of all urls within the site.', prod_check_link_array($title, 'http://drupal.org/project/xmlsitemap')),
    '#nagios_key' => 'XMLS',
    '#nagios_type' => 'state',
  );

  return prod_check_execute_check($check, $caller);
}
